apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment        # lowercase, DNS-compliant name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend                # must match template labels
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend-container
          image: nginx:latest
          ports:
            - containerPort: 80    # expose port 80 (nginx default)

