apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment       # lowercase, DNS-compliant
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend-container
          image: nginx:latest
          ports:
            - containerPort: 80   # expose Nginx default port
          resources:              # optional but recommended
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
